## cc=read.table("usernumdatahtcc2.txt")
## agw=read.table("usernumdatahtagw2.txt")
## gw=read.table("usernumdatahtgw2.txt")

## plot(V2 ~ V1, cc, xlab="Time", ylab="# of unique users", ylim=c(0,90000), main="Plot of unique users against time (UNIX time) for each hashtag")
## lines(V2 ~ V1, cc, xlab="Time", ylab="# of unique users")
## points(V2 ~ V1, gw, xlab="Time", ylab="# of unique users", col="red")
## lines(V2 ~ V1, gw, xlab="Time", ylab="# of unique users", col="red")
## points(V2 ~ V1, agw, xlab="Time", ylab="# of unique users", col="blue")
## lines(V2 ~ V1, agw, xlab="Time", ylab="# of unique users", col="blue")
## legend(1.358E9,80000, c("#climatechange (current 86410)","#globalwarming (current 56526)","#agw (current 3081)"),lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","red", "blue")
## )
## dev.copy(png, "uuplot.png")
## dev.off()

## cc=read.table("acttweetdatahtclimatechange3.txt")
## agw=read.table("acttweetdatahtagw3.txt")
## gw=read.table("acttweetdatahtglobalwarming3.txt")

## plot(V2 ~ V1, cc, xlab="Time", ylab="# of tweets per day", ylim=c(0,10000), main="Plot of tweets per day against time (UNIX time) for each hashtag")
## lines(V2 ~ V1, cc, xlab="Time", ylab="# of tweets per day")
## points(V2 ~ V1, gw, xlab="Time", ylab="# of tweets per day", col="red")
## lines(V2 ~ V1, gw, xlab="Time", ylab="# of tweets per day", col="red")
## points(V2 ~ V1, agw, xlab="Time", ylab="# of tweets per day", col="blue")
## lines(V2 ~ V1, agw, xlab="Time", ylab="# of tweets per day", col="blue")
## legend(1.362E9,8000, c("#climatechange","#globalwarming","#agw"),lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","red", "blue")
## )
## dev.copy(png, "actplot.png")
## dev.off()

cc=read.table("tweetnumdatahtclimatechange3.txt")
gw=read.table("tweetnumdatahtglobalwarming3.txt")
agw=read.table("tweetnumdatahtagw3.txt")

plot(V2 ~ V1, cc, xlab="Time", ylab="# of cumulative tweets", ylim=c(0,250000), main="Plot of cumulative tweets against time (UNIX time) for each hashtag")
lines(V2 ~ V1, cc, xlab="Time", ylab="# of cumulative tweets")
points(V2 ~ V1, gw, xlab="Time", ylab="# of cumulative tweets", col="red")
lines(V2 ~ V1, gw, xlab="Time", ylab="# of cumulative tweets", col="red")
points(V2 ~ V1, agw, xlab="Time", ylab="# of cumulative tweets", col="blue")
lines(V2 ~ V1, agw, xlab="Time", ylab="# of cumulative tweets", col="blue")
legend(1.36E9,200000, c("#climatechange","#globalwarming","#agw"),lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","red", "blue")
)
dev.copy(png, "ctplot.png")
dev.off()
